### ISSUE TITLE
Allow to configure resources for backrest-sidecar container

### ISSUE THREAD

**Issue by tomix86** [cscetbon/casskop#107]
## Feature Request

**Is your feature request related to a problem? Please describe.**
We are utilizing our own backup implementation for Cassandra and the real resources usage by `backrest-sidecar` container is substantially below the requests/limits currently set. We have confirmed this by inspecting the historical data in our monitoring solution.
Therefore, we'd like to lower the requests/limits for the `backrest-sidecar` so that we can assign them to the primary `cassandra` container, while keeping Guaranteed QoS class.
The business justification for that is to optimize the utilization of nodes and consequently lower the costs by having to scale-out later.

**Describe the solution you'd like to see**
A possibility to set resources for `backrest-sidecar` via `values.yaml`

**Describe alternatives you've considered**
There's no alternative currently as resources are hardcoded in casskop code.

**Comment by AKamyshnikova** [comment]
@tomix86 You can set resources via cassandraclusters custom resource
``` 
spec:
   backRestSidecar:
      resources:
```

**Comment by cscetbon** [comment]
@tomix86 as indicated by @AKamyshnikova you can change that as you can see at https://github.com/cscetbon/casskop/blob/master/charts/casskop/crds/db.orange.com_cassandraclusters.yaml#L44-L64.

**Comment by tomix86** [comment]
That solves my use-case indeed and I can confirm that it works, thank you for assistance.
