### ISSUE TITLE
No matches for kind "MultiCasskop" in version "multicasskops.db.orange.com/v2"

### ISSUE THREAD

**Issue by Subetov** [cscetbon/casskop#123]
## Bug Report

**What did you do?**
`helm install  multi-casskop oci://ghcr.io/cscetbon/multi-casskop-helm`

**What did you expect to see?**
multi-casskop up and running

**What did you see instead? Under which circumstances?**
Crashloopback with error:
`creating Cassandra Multi Cluster controller: setting up MultiCasskop watch in Cluster dc1 Cluster: no matches for kind "MultiCasskop" in version "multicasskops.db.orange.com/v2"`

**Environment**
* casskop version:

2.1.17

* Kubernetes version information:

v1.27.3

**k api-versions | grep orange**
```
db.orange.com/v1
db.orange.com/v1alpha1
db.orange.com/v2
```

**k api-resources | grep orange**
```
cassandrabackups                               db.orange.com/v2                       true         CassandraBackup
cassandraclusters                              db.orange.com/v2                       true         CassandraCluster
cassandrarestores                              db.orange.com/v2                       true         CassandraRestore
multicasskops                                  db.orange.com/v2                       true         MultiCasskop
```

**k get crd multicasskops.db.orange.com -o yaml**
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2023-08-02T13:48:08Z"
  generation: 1
  name: multicasskops.db.orange.com
  resourceVersion: "14831"
  uid: 9f43d154-3e16-47c7-91c7-d1bba77968c1
spec:
  conversion:
    strategy: None
  group: db.orange.com
  names:
    kind: MultiCasskop
    listKind: MultiCasskopList
    plural: multicasskops
    singular: multicasskop
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        required:
        - metadata
        - spec
        type: object
    served: true
    storage: false
  - name: v2
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        required:
        - metadata
        - spec
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: MultiCasskop
    listKind: MultiCasskopList
    plural: multicasskops
    singular: multicasskop
  conditions:
  - lastTransitionTime: "2023-08-02T13:48:08Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2023-08-02T13:48:08Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v2
```

**Comment by cscetbon** [comment]
@Subetov you didn't specify any local and remote clusters, see https://cscetbon.github.io/casskop/docs/setup/multi_casskop

**Comment by Subetov** [comment]
I testes that with one (this case worked perfectly with 2.0.3 ) and two clusters, got the same errors =(
I can't figure out why this error occurs, since all the CRDs are in place and have version 2, as you can see from the output of the commands above.

**Comment by cscetbon** [comment]
Can you try different version starting from `2.0.4` and tell us when it starts to fail ? and you're saying `2.0.3` with the exact k8s version works, correct ?

**Comment by cscetbon** [comment]
Even better @Subetov can you try to install casskop and multi-casskop but using our master tag instead
```
helm install  multi-casskop oci://ghcr.io/cscetbon/multi-casskop-helm --set image.tag=master
```
It would confirm that create a new release would fix your issue.

**Comment by Subetov** [comment]
Got the same result with ghcr.io/cscetbon/multi-casskop:master image =(

```
I0821 08:50:14.205969       1 request.go:665] Waited for 1.027928731s due to client-side throttling, not priority and fairness, request: GET:https://10.99.20.1:443/apis/snapshot.storage.k8s.io/v1beta1?timeout=32s
2023/08/21 08:50:14 creating Cassandra Multi Cluster controller: setting up MultiCasskop watch in Cluster dc1 Cluster: no matches for kind "MultiCasskop" in version "multicasskops.db.orange.com/v2"
```

**Comment by cscetbon** [comment]
Sorry I was confused by another PR. Here the issue is not the image but the CRDs. But it doesn't make sense as they are present in your output. It seems to be an issue with your cluster dc1 but not sure what's going on. Are you sure you're connected to the right cluster ? Can you describe step by step what you're doing to set it up ?

**Comment by Subetov** [comment]
Just trying to deploy multi-casskop.
`helm upgrade -i multi-casskop oci://ghcr.io/cscetbon/multi-casskop-helm --set k8s.local=k8s-cluster1 --set-json k8s.remote={} -n cassandra --create-namespace`

This works perfectly with 2.0.3 multi-casskop operator for us.
It makes no difference whether I specify a remote cluster or leave the list empty. The operator cannot find the CRD (locally)

```
time="2023-08-23T05:59:17Z" level=info msg="Go Version: go1.19.10"
time="2023-08-23T05:59:17Z" level=info msg="Go OS/Arch: linux/amd64"
time="2023-08-23T05:59:17Z" level=info msg="multi-casskop Version: "
time="2023-08-23T05:59:17Z" level=info msg="multi-casskop Compilation Date: "
time="2023-08-23T05:59:17Z" level=info msg="Configuring Client for local cluster k8s-cluster1. using local k8s api access"
time="2023-08-23T05:59:17Z" level=info msg="Creating Controller"
time="2023-08-23T05:59:17Z" level=info msg="Create Client for local Cluster k8s-cluster1"
time="2023-08-23T05:59:17Z" level=info msg="Add CRDs to Cluster k8s-cluster1 Scheme"
time="2023-08-23T05:59:17Z" level=info msg="Configuring Watch for MultiCasskop on local"
2023/08/23 05:59:17 creating Cassandra Multi Cluster controller: setting up MultiCasskop watch in Cluster k8s-cluster1 Cluster: no matches for kind "MultiCasskop" in version "multicasskops.db.orange.com/v2"
```

**Comment by cscetbon** [comment]
Can you try the same but testing using installing the helm chart from the repo itself ?
Take a look at how we do it in our e2e GitHub workflow

**Comment by Subetov** [comment]
> Can you try the same but testing using installing the helm chart from the repo itself ? Take a look at how we do it in our e2e GitHub workflow


Do you mean just to install charts from [these folders](https://github.com/cscetbon/casskop/tree/master/charts) from master branch ?

**Comment by cscetbon** [comment]
> > Can you try the same but testing using installing the helm chart from the repo itself ? Take a look at how we do it in our e2e GitHub workflow
> 
> 
> 
> 
> 
> Do you mean just to install charts from [these folders](https://github.com/cscetbon/casskop/tree/master/charts) from master branch ?

Yes. I wanna see if it's something that has been fixed and not delivered or not before I test it myself

**Comment by cscetbon** [comment]
@Subetov any news ?

**Comment by Subetov** [comment]
Got the same results =(
(Had to use --set image.tag=master)

**Comment by cscetbon** [comment]
Annoying ... @AKamyshnikova do you use multi-casskop ? I wonder what could be the issue here and if we broke something or if it's a permission issue somehow ...

**Comment by AKamyshnikova** [comment]
@cscetbon I didn't use multi-casskop - I cheked its CRD and looked wrong version and versions fields https://github.com/cscetbon/casskop/blob/master/multi-casskop/config/crd/bases/multicasskops.db.orange.com_multicasskops.yaml#L15-L16 
Seems it is not generated by controller-gen. Guess this is by design.

@Subetov General concern about kubernetes v1.27.3 - you checked 2.0.3 with v1.27.3 or early kubernetes versions?

**Comment by cscetbon** [comment]
> @cscetbon I didn't use multi-casskop - I cheked its CRD and looked wrong version and versions fields https://github.com/cscetbon/casskop/blob/master/multi-casskop/config/crd/bases/multicasskops.db.orange.com_multicasskops.yaml#L15-L16 Seems it is not generated by controller-gen. Guess this is by design.

It's supposed to be generated using https://github.com/cscetbon/casskop/blob/master/multi-casskop/Makefile#L61-L66

**Comment by cscetbon** [comment]
Is your PR @AKamyshnikova supposed to be fix this ?

**Comment by cscetbon** [comment]
@AKamyshnikova do you have some time to take a look ?

**Comment by AKamyshnikova** [comment]
@cscetbon @Subetov Hopefully will be able to dig into this on this week

**Comment by Subetov** [comment]
Should we expect a new release?

**Comment by AKamyshnikova** [comment]
@Subetov Yes, I hope to do it this week.

**Comment by Subetov** [comment]
@cscetbon @AKamyshnikova 
Hello guys.
I'm getting the same result =( (multi-casskop-helm:2.1.19)
Don't know how you were able to make it works.
**helm upgrade -i multi-casskop oci://ghcr.io/cscetbon/multi-casskop-helm --set k8s.local=k8s-cluster1 --set-json k8s.remote={}**
`2024/03/24 12:19:06 creating Cassandra Multi Cluster controller: setting up MultiCasskop watch in Cluster k8s-cluster1 Cluster: no matches for kind "MultiCasskop" in version "multicasskops.db.orange.com/v2"`

I see that Anna in [PR-131](https://github.com/cscetbon/casskop/pull/131) has tested multi-casskop with "image.tag=multi-casskop". Do not know what this tag is, but it doesn't exist.

**Comment by AKamyshnikova** [comment]
@Subetov Please use [v2.2.0](https://github.com/cscetbon/casskop/releases/tag/v2.2.0) release it will contain the fix you've mentioned.

**Comment by Subetov** [comment]
@AKamyshnikova It looks like I mixed up the release and didn't use the latest one, thanks.
Sorry for the inconvenience

**Comment by Subetov** [comment]
@AKamyshnikova 
helm install multi-casskop oci://ghcr.io/cscetbon/multi-casskop-helm --set k8s.local=dc1 --set-json k8s.remote={}
**Pulled: ghcr.io/cscetbon/multi-casskop-helm:2.1.19**
Seems like 2.1.19 is the latest one in oci://ghcr.io/cscetbon/multi-casskop and casskop repo.

**Comment by AKamyshnikova** [comment]
@Subetov I published new https://github.com/cscetbon/casskop/releases/tag/2.2.2 - seems now it is correct:

```
helm install multi-casskop oci://ghcr.io/cscetbon/multi-casskop-helm --set k8s.local=dc1 --set-json k8s.remote={}
Pulled: ghcr.io/cscetbon/multi-casskop-helm:2.2.2
Digest: sha256:494c872a4524635150d2783c1e08af71091f8cc82cb59165aa0ffdc5792d14bd```

**Comment by Subetov** [comment]
@AKamyshnikova 
Thank you !
