### ISSUE TITLE
[Question] HEAP SETTINGS

### ISSUE THREAD

**Issue by Subetov** [cscetbon/casskop#141]
## Type of question

Configuring HEAP SETTING for CassandraCluster resource

## Question

Could you tell me which method is the most correct for the hip size configuration?

For example is it possible to configure -Xms/-Xmx with CassandraCluster / MultiCasskop resource, like log_gc here ?
![image](https://github.com/cscetbon/casskop/assets/5689355/256e857d-701b-4540-9df4-695a3218b1ce)

**Comment by AKamyshnikova** [comment]
@Subetov Yes, you can pass parameters like `initial_heap_size`, `max_heap_size` in this section

**Comment by Subetov** [comment]
This probably doesn't work for Cassandra 4.1.4 / config-builder 1.0.8
```
Error processing request: throw+: {:type :InvalidConfigKeys, :message "Invalid config keys for DSE version 4.1.4: max_heap_size"}
```

**Comment by AKamyshnikova** [comment]
@Subetov My guess is that you require a feature request for 4.1.4 Cassandra support.
