### ISSUE TITLE
No versioned tags after 2.1.4

### ISSUE THREAD

**Issue by pitwegner** [cscetbon/casskop#53]
## Bug Report

**What did you do?**
Trying to pull `ghcr.io/cscetbon/casskop:2.1.9`, I realized that `2.1.4` is the last available tag on the repo. However, `latest` was correctly pushed.

**What did you expect to see?**
All releases to be pushed as versioned tags to the docker registry.

**Comment by cscetbon** [comment]
Wow thanks for reporting this I need to fix this 🤦‍♂️
