### ISSUE TITLE
Can't deploy multi-casskop helm chart

### ISSUE THREAD

**Issue by Subetov** [cscetbon/casskop#56]
## Bug Report
**What did you do?**
`helm upgrade -i multi-casskop -n cassandra oci://ghcr.io/cscetbon/multi-casskop-helm`

**What did you expect to see?**
Helm release is installed

**What did you see instead? Under which circumstances?**
`Release "multi-casskop" does not exist. Installing it now.
W0811 14:27:06.527598    4079 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Error: failed to install CRD crds/db.orange.com_multicasskops.yaml: CustomResourceDefinition.apiextensions.k8s.io "multicasskops.db.orange.com" is invalid: spec.version: Invalid value: "v2": must match the first version in spec.versions`

**Environment**
* casskop version:

2.1.9

* Kubernetes version information:

v1.21.4

**Comment by cscetbon** [comment]
@Subetov Can you try #60 ?
Clone that repo, checkout branch api-deprecated and install it using something like
```
helm install multi-casskop  charts/multi-casskop/
```

**Comment by Subetov** [comment]
@cscetbon It worked.
