### ISSUE TITLE
Documentation issue ?

### ISSUE THREAD

**Issue by Subetov** [cscetbon/casskop#57]
## Type of question

Documentation issue

## Question

I'm curious why everywhere in the 'Helm installation' step [documentation](https://cscetbon.github.io/casskop/docs/setup/getting_started/#installing-casskop-with-helm-3) says to add one repository, and in the next step, the installation of the Helm Chart is done from another repository.

1. Adding helm repo
2. Installing release from OCI registry
```
helm repo add orange-incubator https://orange-kubernetes-charts-incubator.storage.googleapis.com/
```
```
helm install casskop oci://ghcr.io/cscetbon/casskop-helm
```

Thanks.

**Comment by cscetbon** [comment]
@Subetov my bad, it's because in the past another repo was used and I forgot to remove that first line. Will do it. Thanks for reporting it !
