### ISSUE TITLE
Services are not headless anymore

### ISSUE THREAD

**Issue by zanettea** [cscetbon/casskop#85]
From version 2.1.13 to 2.1.14 the cassandra services created are not headless anymore. 

I don't know if the change was intended... anyway is a big breaking change that should go in a major.

**Comment by rocket357** [comment]
I closed #84 as the behavior noted there is explained by the service not being created headless in 2.1.14 now.  Will defer to this issue since it points more directly to the cause.  =)

**Comment by cscetbon** [comment]
@zanettea hmm it wasn't intended and I think we thought it was headless by default 😕. Going to make a PR to revert it ...

**Comment by cscetbon** [comment]
@zanettea can you confirm PR #86 fixes it ? You can overwrite the image installed by helm by adding `--set image.tag=headless-service` to the helm install command

**Comment by cscetbon** [comment]
@zanettea 👆

**Comment by cscetbon** [comment]
@zanettea as I didn't get any response I'll merge that PR which solves the issue described.
