### ISSUE TITLE
Casskop doesn't work properly on Kubernetes 1.25.x

### ISSUE THREAD

**Issue by ajoskowski** [cscetbon/casskop#99]
## Bug Report
We have deployed casskop operator on Kubernetes 1.24.x.
Now we want to use it on Kubernetes 1.25.x.
We are not able to do it, because casskop uses "beta" APIs - example for [PodDisruptionBudget](https://github.com/cscetbon/casskop/blob/master/controllers/cassandracluster/poddisruptionbudget.go#L21)

**What did you expect to see?**
I would like to be able to use casskop on Kubernetes 1.25.x

**What did you see instead? Under which circumstances?**
```
2023-04-05T10:53:05.629Z        INFO    controller_cassandracluster     Reconciling CassandraCluster    {"Request.Namespace": "prod-doaks-cassandra", "Request.Name": "cassandra-cluster"}
time="2023-04-05T10:53:06Z" level=error msg="CreateOrUpdatePodDisruptionBudget Error: no matches for kind \"PodDisruptionBudget\" in version \"policy/v1beta1\""
time="2023-04-05T10:53:06Z" level=error msg="ensureCassandraPodDisruptionBudget Error: no matches for kind \"PodDisruptionBudget\" in version \"policy/v1beta1\"" cluster=cassandra-cluster
time="2023-04-05T10:53:06Z" level=info msg="We will request : cassandra-cluster-dc1-rack1-0.cassandra-cluster to catch hostIdMap" cluster=cassandra-cluster err="<nil>"
```

**Environment**
* casskop version: `2.1.0-release`

* Kubernetes version information: Azure AKS 1.25.4

**Possible Solution**
Replace "beta" apis with stable ones

**Comment by cscetbon** [comment]
I wonder if there is somehow a way to be compatible with both. If we make this change then it won't run on older versions of k8s AFAIU ...

**Comment by cscetbon** [comment]
Okay it seems it's been promoted in 1.21 so I think it's safe to upgrade. @ajoskowski please create a PR

**Comment by ajoskowski** [comment]
@cscetbon Could you merge it?

**Comment by cscetbon** [comment]
Thanks @ajoskowski for your contribution !

**Comment by ajoskowski** [comment]
@cscetbon When do you plan to release this version?
